"""
services/ai-agent/tools/github_pr.py

Agent tool: create_github_pr

Creates a branch in the cartesi-rvp repo, writes suggested test definition
files to tests/definitions/, then opens a GitHub pull request.

Used by:
  - The PR analysis consumer (consumers/pr_analysis.py) for auto-PR when confidence is high
  - The agent loop when the agent calls create_github_pr via tool use
"""
import base64
import json
import logging
import os
from datetime import datetime, timezone

import httpx

log = logging.getLogger("ai-agent.tools.github_pr")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO  = os.getenv("GITHUB_RVP_REPO", "cartesi/cartesi-rvp")  # the RVP repo (not the node repo)
GH_API       = "https://api.github.com"

HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "Authorization": f"Bearer {GITHUB_TOKEN}",
}


class GitHubPRError(Exception):
    pass


async def _get_default_branch(client: httpx.AsyncClient) -> str:
    resp = await client.get(f"{GH_API}/repos/{GITHUB_REPO}", headers=HEADERS)
    resp.raise_for_status()
    return resp.json().get("default_branch", "main")


async def _get_branch_sha(client: httpx.AsyncClient, branch: str) -> str:
    resp = await client.get(f"{GH_API}/repos/{GITHUB_REPO}/git/ref/heads/{branch}", headers=HEADERS)
    resp.raise_for_status()
    return resp.json()["object"]["sha"]


async def _create_branch(client: httpx.AsyncClient, branch_name: str, sha: str) -> None:
    resp = await client.post(
        f"{GH_API}/repos/{GITHUB_REPO}/git/refs",
        headers=HEADERS,
        json={"ref": f"refs/heads/{branch_name}", "sha": sha},
    )
    if resp.status_code == 422 and "already exists" in resp.text:
        log.info("Branch %s already exists — reusing", branch_name)
        return
    resp.raise_for_status()


async def _upsert_file(
    client: httpx.AsyncClient,
    branch: str,
    path: str,
    content: str,
    message: str,
) -> None:
    """Create or update a file in the repo via the Contents API."""
    # Check if file exists to get its SHA (needed for update)
    check = await client.get(
        f"{GH_API}/repos/{GITHUB_REPO}/contents/{path}",
        headers=HEADERS,
        params={"ref": branch},
    )
    file_sha = check.json().get("sha") if check.status_code == 200 else None

    payload: dict = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "branch": branch,
    }
    if file_sha:
        payload["sha"] = file_sha

    resp = await client.put(
        f"{GH_API}/repos/{GITHUB_REPO}/contents/{path}",
        headers=HEADERS,
        json=payload,
    )
    resp.raise_for_status()


async def _open_pr(
    client: httpx.AsyncClient,
    branch: str,
    base: str,
    title: str,
    body: str,
) -> dict:
    resp = await client.post(
        f"{GH_API}/repos/{GITHUB_REPO}/pulls",
        headers=HEADERS,
        json={
            "title": title,
            "head": branch,
            "base": base,
            "body": body,
        },
    )
    if resp.status_code == 422 and "pull request already exists" in resp.text.lower():
        # Return existing PR URL
        list_resp = await client.get(
            f"{GH_API}/repos/{GITHUB_REPO}/pulls",
            headers=HEADERS,
            params={"head": f"{GITHUB_REPO.split('/')[0]}:{branch}", "state": "open"},
        )
        prs = list_resp.json()
        return prs[0] if prs else {}
    resp.raise_for_status()
    return resp.json()


async def create_github_pr(inputs: dict, _ctx: dict) -> dict:
    """
    Create a GitHub PR with suggested test definition files.

    inputs:
      branch  — branch name (e.g. "auto-test/v1.5.0-suggestions")
      files   — list of {"path": "tests/definitions/foo.md", "content": "..."}
      title   — PR title
      body    — PR description (markdown)
    """
    if not GITHUB_TOKEN:
        return {"error": "GITHUB_TOKEN not set — cannot create GitHub PR"}

    branch: str  = inputs.get("branch", f"auto-test/{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}")
    files: list  = inputs.get("files", [])
    title: str   = inputs.get("title", "AI-suggested test definitions")
    body: str    = inputs.get("body", "Auto-generated by Cartesi RVP AI Agent.")

    if not files:
        return {"error": "No files provided — nothing to commit"}

    async with httpx.AsyncClient(timeout=30) as client:
        try:
            default_branch = await _get_default_branch(client)
            head_sha       = await _get_branch_sha(client, default_branch)

            await _create_branch(client, branch, head_sha)

            for file_spec in files:
                path    = file_spec.get("path", "")
                content = file_spec.get("content", "")
                if not path or not content:
                    continue
                await _upsert_file(
                    client, branch, path, content,
                    message=f"feat(tests): add AI-suggested test definition\n\n{title}"
                )
                log.info("Wrote %s to branch %s", path, branch)

            # Add labels tag to PR body
            full_body = (
                f"{body}\n\n---\n"
                f"_Auto-generated by Cartesi RVP AI Agent. "
                f"Review carefully before merging._\n\n"
                f"**Labels:** `ai-suggested`, `needs-review`"
            )

            pr = await _open_pr(client, branch, default_branch, title, full_body)

            # Try to add labels (non-fatal if it fails)
            try:
                await client.post(
                    f"{GH_API}/repos/{GITHUB_REPO}/issues/{pr['number']}/labels",
                    headers=HEADERS,
                    json={"labels": ["ai-suggested", "needs-review"]},
                )
            except Exception:
                pass

            return {
                "pr_number":  pr.get("number"),
                "pr_url":     pr.get("html_url", ""),
                "branch":     branch,
                "files_written": len(files),
                "status":     "created",
            }

        except httpx.HTTPStatusError as e:
            log.error("GitHub API error: %s %s", e.response.status_code, e.response.text[:200])
            return {"error": f"GitHub API error {e.response.status_code}: {e.response.text[:200]}"}
        except Exception as e:
            log.error("create_github_pr failed: %s", e)
            return {"error": str(e)}
