# Load pre-declared exchanges/queues/bindings on boot
load_definitions = /etc/rabbitmq/definitions.json

# Management plugin
management.load_definitions = /etc/rabbitmq/definitions.json

# Reasonable defaults
vm_memory_high_watermark.relative = 0.6
disk_free_limit.relative = 1.0
